name: Control Ventas - CI Pipeline

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs: #conjunto de tareas
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Dando permisos de ejecucion para Maven Wrapper
        run: chmod +x ./mvnw

      - name: Build JAR
        run: ./mvnw clean package

