name: Control Ventas - CI Pipeline

on:
  push:
    branches:
      - dev
      - main
  pull_request:
    branches:
      - dev
      - main

jobs: #conjunto de tareas
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Check out code
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Dando permisos de ejecucion para Maven Wrapper
        run: chmod +x ./mvnw

      - name: Run Tests
        run: ./mvnw test

      - name: Build JAR (sin omitir tests)
        run: ./mvnw clean package -DskipTests=false

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_PASSWORD }}

      - name: Build Docker image
        run: docker build -t luisorihuela92/control-ventas:latest . #de esta manera manejamos los tags y las versiones

      - name: Push Docker image to Docker Hub
        run: docker push luisorihuela92/control-ventas:latest

